[env:stm32f412]
platform = ststm32
board = genericSTM32F412RE
framework = arduino

board_build.mcu = stm32f412ret6
board_build.f_cpu = 100000000L

lib_deps =
    olikraus/U8g2@^2.35
    greiman/SdFat@^2.2

build_flags =
    -D HAL_UART_MODULE_ENABLED
    -D HAL_ADC_MODULE_ENABLED
    -D HAL_TIM_MODULE_ENABLED
    -D HAL_I2C_MODULE_ENABLED
    -D HAL_SD_MODULE_ENABLED
    -D SERIAL_UART_INSTANCE=2

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
